name: ci
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        package: ['a', 'b']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests
        run: exit 0

  bors:
    name: Bors
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
        - run: exit 0
